---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared.vol
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    server: k8s-master # IP address of your NFS service
    path: "/share/nfs"
